# Grantmaker settings
foundation_name: The LightBridge Foundation
foundation_tagline: We provide artificial intelligence where internet access is impossible.
grant_application_login: https://www.grantinterface.com/Common/LogOn.aspx?eqs=kw_123456_EXAMPLE

# Social media settings
# Enter the full profile url (e.g. https://twitter.com/smartergiving)
profile_twitter: 
profile_facebook: 
profile_instagram: 
profile_github: 

# Site settings
title: # Defaults to foundation_name if left blank
description: > # this means to start on the next line (which needs to be indented two spaces)"
  The LightBridge Foundation works in rural communities to provide artificial intelligence where internet access is impossible. We work primarily in Sub-Saharan Africa and Europe.

# Google settings
live: true

# Jekyll settings
baseurl:  # Leave this blank unless your site is located on a subpath, e.g. /blog
url: https://lightbridge.foundation # Typically http://www.yourdomain.org
collections:
  featured-cards:
    output: true
sass:
  sass_dir: assets/css/_sass

# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: 
  - README.md
  - /images/photoshop-helpers
